# Syndicate core
#
# VERSION	1.0

FROM	syndicate-base
MAINTAINER	Illyoung Choi <iychoi@email.arizona.edu>

##############################################
# Setup Syndicate
##############################################
USER root

ENV APT_KEY butler_opencloud_cs_arizona_edu_pub.gpg

# Prep apt to be able to download over https
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --force-yes\
    apt-transport-https

# Copy over and trust https cert
COPY butler.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

# Install Syndicate
COPY $APT_KEY /tmp/
RUN apt-key add /tmp/$APT_KEY

RUN echo "deb https://butler.opencloud.cs.arizona.edu/repos/release/syndicate syndicate main" > /etc/apt/sources.list.d/butler.list

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --force-yes\
    syndicate-core \
    valgrind

USER $USER
WORKDIR $HOME
