# Syndicate Base
#
# VERSION	1.0

FROM	ubuntu:14.04
MAINTAINER	Illyoung Choi <iychoi@email.arizona.edu>

##############################################
# Setup environment
##############################################
ENV LD_LIBRARY_PATH /usr/local/lib

##############################################
# Setup a Syndicate account
##############################################
ENV HOME /home/syndicate

RUN useradd syndicate && echo 'syndicate:syndicate' | chpasswd && \
    echo "syndicate ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir /home/syndicate && \
    chown -R syndicate:syndicate $HOME

ENV USER syndicate
WORKDIR $HOME

##############################################
# Setup utility packages
##############################################
RUN apt-get update && \
    apt-get install -y wget curl unzip python-pip build-essential ssh tcpdump fuse && \
    sudo usermod -aG fuse $USER

USER $USER
WORKDIR $HOME
